name: bankid_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_svg: ^2.2.3
  hugeicons: ^1.1.5
  image_picker: ^1.2.1
  file_picker: ^10.3.10
  path_provider: ^2.1.5
  image: ^4.7.2
  crop_your_image: ^2.0.0

  permission_handler: ^12.0.1
  permission_handler_android: ^13.0.1
  google_fonts: ^8.0.1

  characters: ^1.4.0
  material_color_utilities: ^0.11.1
  meta: ^1.17.0
  shared_preferences: ^2.5.4
  local_auth: ^3.0.0
  local_auth_android: ^2.0.0
  local_auth_darwin: ^2.0.0
  pinput: ^6.0.2
  flutter_gen: ^5.12.0
  qr_flutter: ^4.1.0
  http: ^1.6.0
  url_launcher: ^6.3.1
  flutter_secure_storage: ^10.0.0
  flutter_dotenv: ^6.0.0
  flutter_screenutil: ^5.9.3
  mobile_scanner: ^7.1.4
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  logger: ^2.6.2
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  device_info_plus: ^11.0.0
  package_info_plus: ^8.0.0
  flutter_pdfview: ^1.4.4
  syncfusion_flutter_pdfviewer: ^31.1.21
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_api: ^0.7.7
  flutter_lints: ^6.0.0
  mockito: ^5.6.3
  build_runner: ^2.11.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/bankid_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - .env