class CountryUtils {
  static const Map<String, Map<String, String>> _countryMap = {
    // Alpha-3 codes
    'AFG': {'en': 'Afghanistan', 'ar': 'أفغانستان'},
    'ALB': {'en': 'Albania', 'ar': 'ألبانيا'},
    'DZA': {'en': 'Algeria', 'ar': 'الجزائر'},
    'AND': {'en': 'Andorra', 'ar': 'أندورا'},
    'AGO': {'en': 'Angola', 'ar': 'أنغولا'},
    'ARG': {'en': 'Argentina', 'ar': 'الأرجنتين'},
    'ARM': {'en': 'Armenia', 'ar': 'أرمينيا'},
    'AUS': {'en': 'Australia', 'ar': 'أستراليا'},
    'AUT': {'en': 'Austria', 'ar': 'النمسا'},
    'AZE': {'en': 'Azerbaijan', 'ar': 'أذربيجان'},
    'BHR': {'en': 'Bahrain', 'ar': 'البحرين'},
    'BGD': {'en': 'Bangladesh', 'ar': 'بنغلاديش'},
    'BEL': {'en': 'Belgium', 'ar': 'بلجيكا'},
    'BRA': {'en': 'Brazil', 'ar': 'البرازيل'},
    'CAN': {'en': 'Canada', 'ar': 'كندا'},
    'CHN': {'en': 'China', 'ar': 'الصين'},
    'COL': {'en': 'Colombia', 'ar': 'كولومبيا'},
    'CUB': {'en': 'Cuba', 'ar': 'كوبا'},
    'CYP': {'en': 'Cyprus', 'ar': 'قبرص'},
    'CZE': {'en': 'Czechia', 'ar': 'تشيكيا'},
    'DNK': {'en': 'Denmark', 'ar': 'الدنمارك'},
    'EGY': {'en': 'Egypt', 'ar': 'مصر'},
    'EST': {'en': 'Estonia', 'ar': 'إستونيا'},
    'ETH': {'en': 'Ethiopia', 'ar': 'إثيوبيا'},
    'FIN': {'en': 'Finland', 'ar': 'فنلندا'},
    'FRA': {'en': 'France', 'ar': 'فرنسا'},
    'GEO': {'en': 'Georgia', 'ar': 'جورجيا'},
    'DEU': {'en': 'Germany', 'ar': 'ألمانيا'},
    'GRC': {'en': 'Greece', 'ar': 'اليونان'},
    'HKG': {'en': 'Hong Kong', 'ar': 'هونغ كونغ'},
    'HUN': {'en': 'Hungary', 'ar': 'المجر'},
    'ISL': {'en': 'Iceland', 'ar': 'آيسلندا'},
    'IND': {'en': 'India', 'ar': 'الهند'},
    'IDN': {'en': 'Indonesia', 'ar': 'إندونيسيا'},
    'IRN': {'en': 'Iran', 'ar': 'إيران'},
    'IRQ': {'en': 'Iraq', 'ar': 'العراق'},
    'IRL': {'en': 'Ireland', 'ar': 'أيرلندا'},
    'ITA': {'en': 'Italy', 'ar': 'إيطاليا'},
    'JPN': {'en': 'Japan', 'ar': 'اليابان'},
    'JOR': {'en': 'Jordan', 'ar': 'الأردن'},
    'KAZ': {'en': 'Kazakhstan', 'ar': 'كازاخستان'},
    'KEN': {'en': 'Kenya', 'ar': 'كينيا'},
    'KWT': {'en': 'Kuwait', 'ar': 'الكويت'},
    'LBN': {'en': 'Lebanon', 'ar': 'لبنان'},
    'LBY': {'en': 'Libya', 'ar': 'ليبيا'},
    'LUX': {'en': 'Luxembourg', 'ar': 'لوكسمبورغ'},
    'MYS': {'en': 'Malaysia', 'ar': 'ماليزيا'},
    'MDV': {'en': 'Maldives', 'ar': 'جزر المالديف'},
    'MLT': {'en': 'Malta', 'ar': 'مالطا'},
    'MEX': {'en': 'Mexico', 'ar': 'المكسيك'},
    'MAR': {'en': 'Morocco', 'ar': 'المغرب'},
    'NLD': {'en': 'Netherlands', 'ar': 'هولندا'},
    'NZL': {'en': 'New Zealand', 'ar': 'نيوزيلندا'},
    'NGA': {'en': 'Nigeria', 'ar': 'نيجيريا'},
    'NOR': {'en': 'Norway', 'ar': 'النرويج'},
    'OMN': {'en': 'Oman', 'ar': 'عُمان'},
    'PAK': {'en': 'Pakistan', 'ar': 'باكستان'},
    'PSE': {'en': 'Palestine', 'ar': 'فلسطين'},
    'PHL': {'en': 'Philippines', 'ar': 'الفلبين'},
    'POL': {'en': 'Poland', 'ar': 'بولندا'},
    'PRT': {'en': 'Portugal', 'ar': 'البرتغال'},
    'QAT': {'en': 'Qatar', 'ar': 'قطر'},
    'ROU': {'en': 'Romania', 'ar': 'رومانيا'},
    'RUS': {'en': 'Russia', 'ar': 'روسيا'},
    'SAU': {'en': 'Saudi Arabia', 'ar': 'المملكة العربية السعودية'},
    'SGP': {'en': 'Singapore', 'ar': 'سنغافورة'},
    'ZAF': {'en': 'South Africa', 'ar': 'جنوب أفريقيا'},
    'KOR': {'en': 'South Korea', 'ar': 'كوريا الجنوبية'},
    'ESP': {'en': 'Spain', 'ar': 'إسبانيا'},
    'LKA': {'en': 'Sri Lanka', 'ar': 'سريلانكا'},
    'SDN': {'en': 'Sudan', 'ar': 'السودان'},
    'SWE': {'en': 'Sweden', 'ar': 'السويد'},
    'CHE': {'en': 'Switzerland', 'ar': 'سويسرا'},
    'SYR': {'en': 'Syria', 'ar': 'سوريا'},
    'TWN': {'en': 'Taiwan', 'ar': 'تايوان'},
    'THA': {'en': 'Thailand', 'ar': 'تايلاند'},
    'TUN': {'en': 'Tunisia', 'ar': 'تونس'},
    'TUR': {'en': 'Turkey', 'ar': 'تركيا'},
    'UKR': {'en': 'Ukraine', 'ar': 'أوكرانيا'},
    'ARE': {'en': 'United Arab Emirates', 'ar': 'الإمارات العربية المتحدة'},
    'GBR': {'en': 'United Kingdom', 'ar': 'المملكة المتحدة'},
    'USA': {'en': 'United States', 'ar': 'الولايات المتحدة'},
    'URY': {'en': 'Uruguay', 'ar': 'أوروغواي'},
    'UZB': {'en': 'Uzbekistan', 'ar': 'أوزبكستان'},
    'VNM': {'en': 'Vietnam', 'ar': 'فيتنام'},
    'YEM': {'en': 'Yemen', 'ar': 'اليمن'},

    // Alpha-2 codes
    'AF': {'en': 'Afghanistan', 'ar': 'أفغانستان'},
    'DZ': {'en': 'Algeria', 'ar': 'الجزائر'},
    'AR': {'en': 'Argentina', 'ar': 'الأرجنتين'},
    'AU': {'en': 'Australia', 'ar': 'أستراليا'},
    'AT': {'en': 'Austria', 'ar': 'النمسا'},
    'BH': {'en': 'Bahrain', 'ar': 'البحرين'},
    'BE': {'en': 'Belgium', 'ar': 'بلجيكا'},
    'BR': {'en': 'Brazil', 'ar': 'البرازيل'},
    'CA': {'en': 'Canada', 'ar': 'كندا'},
    'CN': {'en': 'China', 'ar': 'الصين'},
    'DK': {'en': 'Denmark', 'ar': 'الدنمارك'},
    'EG': {'en': 'Egypt', 'ar': 'مصر'},
    'FR': {'en': 'France', 'ar': 'فرنسا'},
    'DE': {'en': 'Germany', 'ar': 'ألمانيا'},
    'IN': {'en': 'India', 'ar': 'الهند'},
    'ID': {'en': 'Indonesia', 'ar': 'إندونيسيا'},
    'IR': {'en': 'Iran', 'ar': 'إيران'},
    'IQ': {'en': 'Iraq', 'ar': 'العراق'},
    'IE': {'en': 'Ireland', 'ar': 'أيرلندا'},
    'IT': {'en': 'Italy', 'ar': 'إيطاليا'},
    'JP': {'en': 'Japan', 'ar': 'اليابان'},
    'JO': {'en': 'Jordan', 'ar': 'الأردن'},
    'KW': {'en': 'Kuwait', 'ar': 'الكويت'},
    'LB': {'en': 'Lebanon', 'ar': 'لبنان'},
    'LY': {'en': 'Libya', 'ar': 'ليبيا'},
    'MY': {'en': 'Malaysia', 'ar': 'ماليزيا'},
    'MA': {'en': 'Morocco', 'ar': 'المغرب'},
    'NL': {'en': 'Netherlands', 'ar': 'هولندا'},
    'NZ': {'en': 'New Zealand', 'ar': 'نيوزيلندا'},
    'NO': {'en': 'Norway', 'ar': 'النرويج'},
    'OM': {'en': 'Oman', 'ar': 'عُمان'},
    'PK': {'en': 'Pakistan', 'ar': 'باكستان'},
    'PS': {'en': 'Palestine', 'ar': 'فلسطين'},
    'PH': {'en': 'Philippines', 'ar': 'الفلبين'},
    'QA': {'en': 'Qatar', 'ar': 'قطر'},
    'RU': {'en': 'Russia', 'ar': 'روسيا'},
    'SA': {'en': 'Saudi Arabia', 'ar': 'المملكة العربية السعودية'},
    'SG': {'en': 'Singapore', 'ar': 'سنغافورة'},
    'ES': {'en': 'Spain', 'ar': 'إسبانيا'},
    'LK': {'en': 'Sri Lanka', 'ar': 'سريلانكا'},
    'SD': {'en': 'Sudan', 'ar': 'السودان'},
    'SE': {'en': 'Sweden', 'ar': 'السويد'},
    'CH': {'en': 'Switzerland', 'ar': 'سويسرا'},
    'SY': {'en': 'Syria', 'ar': 'سوريا'},
    'TN': {'en': 'Tunisia', 'ar': 'تونس'},
    'TR': {'en': 'Turkey', 'ar': 'تركيا'},
    'AE': {'en': 'United Arab Emirates', 'ar': 'الإمارات العربية المتحدة'},
    'GB': {'en': 'United Kingdom', 'ar': 'المملكة المتحدة'},
    'US': {'en': 'United States', 'ar': 'الولايات المتحدة'},
    'YE': {'en': 'Yemen', 'ar': 'اليمن'},
  };

  static String getCountryName(String code, {String locale = 'en'}) {
    if (code.isEmpty || code == '-') return '-';
    final upperCode = code.toUpperCase().trim();
    final country = _countryMap[upperCode];
    if (country != null) {
      return country[locale] ?? country['en'] ?? code;
    }
    return code;
  }
}
