// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3EVak3gel1mUC6dA-hp7MiL4rrEibYPw',
    appId: '1:585665122067:web:8dc5777b2f5465588fd4e6',
    messagingSenderId: '585665122067',
    projectId: 'bankid-ifin-a2fff',
    authDomain: 'bankid-ifin-a2fff.firebaseapp.com',
    storageBucket: 'bankid-ifin-a2fff.firebasestorage.app',
    measurementId: 'G-X3SNWQGCL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY6OdoRaUvMQgERT16Lql7gmKZfhiPAfY',
    appId: '1:585665122067:android:186d177c84157b8d8fd4e6',
    messagingSenderId: '585665122067',
    projectId: 'bankid-ifin-a2fff',
    storageBucket: 'bankid-ifin-a2fff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWunSZR-LuI-uP0hfsTSIgkyyHIBwH9Lg',
    appId: '1:585665122067:ios:6f44cd36e9d5321e8fd4e6',
    messagingSenderId: '585665122067',
    projectId: 'bankid-ifin-a2fff',
    storageBucket: 'bankid-ifin-a2fff.firebasestorage.app',
    iosBundleId: 'com.example.bankidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWunSZR-LuI-uP0hfsTSIgkyyHIBwH9Lg',
    appId: '1:585665122067:ios:6f44cd36e9d5321e8fd4e6',
    messagingSenderId: '585665122067',
    projectId: 'bankid-ifin-a2fff',
    storageBucket: 'bankid-ifin-a2fff.firebasestorage.app',
    iosBundleId: 'com.example.bankidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3EVak3gel1mUC6dA-hp7MiL4rrEibYPw',
    appId: '1:585665122067:web:cd26177aa72270498fd4e6',
    messagingSenderId: '585665122067',
    projectId: 'bankid-ifin-a2fff',
    authDomain: 'bankid-ifin-a2fff.firebaseapp.com',
    storageBucket: 'bankid-ifin-a2fff.firebasestorage.app',
    measurementId: 'G-ESSSXTXKMY',
  );

}