// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlyFFAmpNW9pIft5c2uEMk2jyUW2GSRRw',
    appId: '1:588638431127:web:69648c85bd40462d8386d2',
    messagingSenderId: '588638431127',
    projectId: 'bankid-ifin',
    authDomain: 'bankid-ifin.firebaseapp.com',
    storageBucket: 'bankid-ifin.firebasestorage.app',
    measurementId: 'G-X62LV7V3QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTa8wZ_pV_0HTiLiTNxSm38W9FtvpPVvE',
    appId: '1:588638431127:android:53a47d45a3d69eb08386d2',
    messagingSenderId: '588638431127',
    projectId: 'bankid-ifin',
    storageBucket: 'bankid-ifin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXSXuRMGB06T1CKUV3yuCceRhOdPQmEQU',
    appId: '1:588638431127:ios:9c41ab10201507308386d2',
    messagingSenderId: '588638431127',
    projectId: 'bankid-ifin',
    storageBucket: 'bankid-ifin.firebasestorage.app',
    iosBundleId: 'com.example.bankidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXSXuRMGB06T1CKUV3yuCceRhOdPQmEQU',
    appId: '1:588638431127:ios:9c41ab10201507308386d2',
    messagingSenderId: '588638431127',
    projectId: 'bankid-ifin',
    storageBucket: 'bankid-ifin.firebasestorage.app',
    iosBundleId: 'com.example.bankidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlyFFAmpNW9pIft5c2uEMk2jyUW2GSRRw',
    appId: '1:588638431127:web:8e838179520ae2f48386d2',
    messagingSenderId: '588638431127',
    projectId: 'bankid-ifin',
    authDomain: 'bankid-ifin.firebaseapp.com',
    storageBucket: 'bankid-ifin.firebasestorage.app',
    measurementId: 'G-NN4B3L2QX8',
  );

}